version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: makinpaham-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: makinpaham
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - makinpaham-network

  redis:
    image: redis:7-alpine
    container_name: makinpaham-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - makinpaham-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  makinpaham-network:
    driver: bridge
